### ISSUE TITLE
Any work for STM32?

### ISSUE THREAD

**Issue by overheat** [mbedmicro/CMSIS-DAP#42]
If not, I can start it.  :)

**Comment by cdwilson** [comment]
What's the status of this?  Is there any "official" mbed support for CMSIS-DAP on the STM32 NUCLEO line in the works?

**Comment by x893** [comment]
You can see mbed cmsis-dap project here
https://github.com/mbedmicro/CMSIS-DAP

**Comment by cdwilson** [comment]
@x893 thanks for the reply.  sorry, maybe a dumb question (I'm new to mbed), but I don't see any support for STM32F103CBT6 on Nucleo F411RE in the repo you linked to.  From the comments above, it looks like you may have added support in https://github.com/x893/CMSIS-DAP but I was wondering if there are plans to merge this work into https://github.com/mbedmicro/CMSIS-DAP ?

**Comment by x893** [comment]
Nucleo F111RE contain STLink V2.1 on board (debugger, serial and flash).
Can't say any about merge because i use V2 (see in HW_STM32\CMSIS-DAP-X893 foler).

**Comment by cdwilson** [comment]
What's the difference between V2 and V2-1?  Do you know if there is anybody actively working on adding support for ST-LINK/V2-1 into https://github.com/mbedmicro/CMSIS-DAP ?  (it sounds like this is a no...)

**Comment by x893** [comment]
V2.1 support serial and flash as disk (see ST or mbed site for details).
Nobody add STLink to CMSIS. STLink close device from ST.

**Comment by c1728p9** [comment]
Looks like there is a PR up for the STM32: https://github.com/mbedmicro/DAPLink/pull/133
