### ISSUE TITLE
license terms

### ISSUE THREAD

**Issue by majbthrd** [mbedmicro/CMSIS-DAP#92]
The LICENSE file packaged with the source code suggests that an Apache license alone applies.  However, the source code practices CMSIS-DAP, whose license:

https://www.keil.com/pack/doc/CMSIS/General/html/CMSIS_END_USER_LICENCE_AGREEMENT.pdf
https://github.com/ARM-software/CMSIS/raw/master/CMSIS/DAP/CMSIS-DAP%20EULA.pdf

is subject to some onerous terms.

In particular, Section 1.5 (CONDITIONS ON REDISTRIBUTION) seems to make anyone who distributes source code for firmware that implements CMSIS-DAP to be liable for how that firmware is used.

With over a hundred forks of this code, this provision seems ill enforced.  However, there is forever the risk that anyone who writes or contributes open source CMSIS-DAP code could become a victim if ARM decides it can monetize the situation.

**Comment by flit** [comment]
CMSIS, and therefore CMSIS-DAP, is licensed via Apache 2.0 now.

**Comment by majbthrd** [comment]
Well, I'm glad that the original onerous 2013-2017 license terms were eventually replaced.  It was a five-year period during which anyone who actually bothered to read the license terms would be reluctant to release open-source code.
